version: '3'
services:
  db1:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=idris
      - POSTGRES_PASSWORD=idris
      - POSTGRES_DB=idris
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "max_prepared_transactions=1"]
  db2:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=idris
      - POSTGRES_PASSWORD=idris
      - POSTGRES_DB=idris
    ports:
      - '5433:5432'
    command: ["postgres", "-c", "max_prepared_transactions=1"]
  db3:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=idris
      - POSTGRES_PASSWORD=idris
      - POSTGRES_DB=idris
    ports:
      - '5434:5432'
    command: ["postgres", "-c", "max_prepared_transactions=1"]

